/* Generated by Yosys 0.60+95 (git sha1 991e70489, g++ 14.3.0 -fPIC -O3) */

module counter(clk, rst, en, \out[0] , \out[1] , \out[2] );
  input clk;
  wire clk;
  input rst;
  wire rst;
  input en;
  wire en;
  output \out[0] ;
  reg \out[0] ;
  output \out[1] ;
  reg \out[1] ;
  output \out[2] ;
  reg \out[2] ;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  assign _02_ = \out[0]  ^ \out[1] ;
  assign _00_ = \out[0]  & \out[1] ;
  assign _03_ = _00_ ^ \out[2] ;
  assign _01_ = ~\out[0] ;
  always @(posedge clk, posedge rst)
    if (rst) \out[0]  <= 1'h0;
    else if (en) \out[0]  <= _01_;
  always @(posedge clk, posedge rst)
    if (rst) \out[1]  <= 1'h0;
    else if (en) \out[1]  <= _02_;
  always @(posedge clk, posedge rst)
    if (rst) \out[2]  <= 1'h0;
    else if (en) \out[2]  <= _03_;
endmodule
