/* Generated by Yosys 0.60+95 (git sha1 991e70489, g++ 14.3.0 -fPIC -O3) */

module counter(clk, rst, en, out);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input en;
  wire en;
  output [2:0] out;
  reg [2:0] out;
  wire _0_;
  wire [2:0] _1_;
  wire [2:0] _2_;
  assign _2_[1] = out[0] ^ out[1];
  assign _0_ = out[0] & out[1];
  assign _2_[2] = _0_ ^ out[2];
  assign _1_[0] = ~out[0];
  always @(posedge clk, posedge rst)
    if (rst) out[0] <= 1'h0;
    else if (en) out[0] <= _1_[0];
  always @(posedge clk, posedge rst)
    if (rst) out[1] <= 1'h0;
    else if (en) out[1] <= _2_[1];
  always @(posedge clk, posedge rst)
    if (rst) out[2] <= 1'h0;
    else if (en) out[2] <= _2_[2];
  assign _1_[2:1] = out[2:1];
  assign _2_[0] = _1_[0];
endmodule
