/* Generated by Yosys 0.60+95 (git sha1 991e70489, g++ 14.3.0 -fPIC -O3) */

module counter(clk, rst, en, \out[0] , \out[1] , \out[2] );
  input clk;
  wire clk;
  input rst;
  wire rst;
  input en;
  wire en;
  output \out[0] ;
  wire \out[0] ;
  output \out[1] ;
  wire \out[1] ;
  output \out[2] ;
  wire \out[2] ;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  \$_XOR_  _04_ (
    .A(\out[0] ),
    .B(\out[1] ),
    .Y(_02_)
  );
  \$_AND_  _05_ (
    .A(\out[0] ),
    .B(\out[1] ),
    .Y(_00_)
  );
  \$_XOR_  _06_ (
    .A(_00_),
    .B(\out[2] ),
    .Y(_03_)
  );
  \$_NOT_  _07_ (
    .A(\out[0] ),
    .Y(_01_)
  );
  \$_DFFE_PP0P_  \out_reg[0]  /* _08_ */ (
    .C(clk),
    .D(_01_),
    .E(en),
    .Q(\out[0] ),
    .R(rst)
  );
  \$_DFFE_PP0P_  \out_reg[1]  /* _09_ */ (
    .C(clk),
    .D(_02_),
    .E(en),
    .Q(\out[1] ),
    .R(rst)
  );
  \$_DFFE_PP0P_  \out_reg[2]  /* _10_ */ (
    .C(clk),
    .D(_03_),
    .E(en),
    .Q(\out[2] ),
    .R(rst)
  );
endmodule
