/* Generated by Yosys 0.62+77 (git sha1 679156d32, g++ 11.5.0 -fPIC -O3) */

module counter(clk, rst, en, \out[0] , \out[1] , \out[2] );
  input clk;
  wire clk;
  input rst;
  wire rst;
  input en;
  wire en;
  output \out[0] ;
  wire \out[0] ;
  output \out[1] ;
  wire \out[1] ;
  output \out[2] ;
  wire \out[2] ;
  wire _0_;
  wire \_1_[0] ;
  wire \_2_[1] ;
  wire \_2_[2] ;
  \$_NOT_  _1_ (
    .A(\out[0] ),
    .Y(\_1_[0] )
  );
  \$_AND_  _2_ (
    .A(\out[1] ),
    .B(\out[0] ),
    .Y(_0_)
  );
  \$_XOR_  _3_ (
    .A(_0_),
    .B(\out[2] ),
    .Y(\_2_[2] )
  );
  \$_XOR_  _4_ (
    .A(\out[1] ),
    .B(\out[0] ),
    .Y(\_2_[1] )
  );
  \$_DFFE_PP0P_  \out_reg[0]  /* _5_ */ (
    .C(clk),
    .D(\_1_[0] ),
    .E(en),
    .Q(\out[0] ),
    .R(rst)
  );
  \$_DFFE_PP0P_  \out_reg[2]  /* _6_ */ (
    .C(clk),
    .D(\_2_[2] ),
    .E(en),
    .Q(\out[2] ),
    .R(rst)
  );
  \$_DFFE_PP0P_  \out_reg[1]  /* _7_ */ (
    .C(clk),
    .D(\_2_[1] ),
    .E(en),
    .Q(\out[1] ),
    .R(rst)
  );
endmodule
