/* Generated by Yosys 0.62+77 (git sha1 679156d32, g++ 11.5.0 -fPIC -O3) */

module counter(clk, rst, en, out);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input en;
  wire en;
  output [2:0] out;
  wire [2:0] out;
  wire _03_;
  wire [2:0] _1_;
  wire [2:0] _2_;
  \$_NOT_  _04_ (
    .A(out[0]),
    .Y(_1_[0])
  );
  \$_AND_  _05_ (
    .A(out[1]),
    .B(out[0]),
    .Y(_03_)
  );
  \$_XOR_  _06_ (
    .A(_03_),
    .B(out[2]),
    .Y(_2_[2])
  );
  \$_XOR_  _07_ (
    .A(out[1]),
    .B(out[0]),
    .Y(_2_[1])
  );
  \$_DFFE_PP0P_  \out_reg[0]  /* _08_ */ (
    .C(clk),
    .D(_1_[0]),
    .E(en),
    .Q(out[0]),
    .R(rst)
  );
  \$_DFFE_PP0P_  \out_reg[2]  /* _09_ */ (
    .C(clk),
    .D(_2_[2]),
    .E(en),
    .Q(out[2]),
    .R(rst)
  );
  \$_DFFE_PP0P_  \out_reg[1]  /* _10_ */ (
    .C(clk),
    .D(_2_[1]),
    .E(en),
    .Q(out[1]),
    .R(rst)
  );
  assign _2_[0] = _1_[0];
  assign _1_[2:1] = out[2:1];
endmodule
