/* Generated by Yosys 0.62+77 (git sha1 679156d32, g++ 11.5.0 -fPIC -O3) */

module counter(clk, rst, en, out);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input en;
  wire en;
  output [2:0] out;
  wire [2:0] out;
  wire _0_;
  wire [2:0] _1_;
  wire [2:0] _2_;
  \$and  #(
    .A_SIGNED(32'h00000000),
    .A_WIDTH(32'h00000001),
    .B_SIGNED(32'h00000000),
    .B_WIDTH(32'h00000001),
    .Y_WIDTH(32'h00000001)
  ) _3_ (
    .A(out[0]),
    .B(out[1]),
    .Y(_0_)
  );
  \$adffe  #(
    .ARST_POLARITY(32'h00000001),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'h00000001),
    .EN_POLARITY(32'h00000001),
    .WIDTH(32'h00000001)
  ) \out_reg[1]  /* _4_ */ (
    .ARST(rst),
    .CLK(clk),
    .D(_2_[1]),
    .EN(en),
    .Q(out[1])
  );
  \$adffe  #(
    .ARST_POLARITY(32'h00000001),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'h00000001),
    .EN_POLARITY(32'h00000001),
    .WIDTH(32'h00000001)
  ) \out_reg[2]  /* _5_ */ (
    .ARST(rst),
    .CLK(clk),
    .D(_2_[2]),
    .EN(en),
    .Q(out[2])
  );
  \$adffe  #(
    .ARST_POLARITY(32'h00000001),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'h00000001),
    .EN_POLARITY(32'h00000001),
    .WIDTH(32'h00000001)
  ) \out_reg[0]  /* _6_ */ (
    .ARST(rst),
    .CLK(clk),
    .D(_1_[0]),
    .EN(en),
    .Q(out[0])
  );
  \$not  #(
    .A_SIGNED(32'h00000000),
    .A_WIDTH(32'h00000001),
    .Y_WIDTH(32'h00000001)
  ) _7_ (
    .A(out[0]),
    .Y(_1_[0])
  );
  \$xor  #(
    .A_SIGNED(32'h00000000),
    .A_WIDTH(32'h00000001),
    .B_SIGNED(32'h00000000),
    .B_WIDTH(32'h00000001),
    .Y_WIDTH(32'h00000001)
  ) _8_ (
    .A(out[0]),
    .B(out[1]),
    .Y(_2_[1])
  );
  \$xor  #(
    .A_SIGNED(32'h00000000),
    .A_WIDTH(32'h00000001),
    .B_SIGNED(32'h00000000),
    .B_WIDTH(32'h00000001),
    .Y_WIDTH(32'h00000001)
  ) _9_ (
    .A(_0_),
    .B(out[2]),
    .Y(_2_[2])
  );
  assign _2_[0] = _1_[0];
  assign _1_[2:1] = out[2:1];
endmodule
